### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by pAkalpa** [judygab/nextjs-searchapp#1]
There is an Error in pages\index.js file.
![error](https://user-images.githubusercontent.com/43250159/167997187-5e92739d-43e6-4c09-97d7-0bbfdec1a8ba.png)

**Comment by judygab** [comment]
Which branch are you using? Because on the main branch I'm seeing different code for that line
<img width="446" alt="Screen Shot 2022-05-17 at 4 19 10 PM" src="https://user-images.githubusercontent.com/50160672/168902876-91f262d5-eff2-49da-8327-457b087a9112.png">

**Comment by pAkalpa** [comment]
I think these issues happen when the API response is empty. When you try to search movie it occurs.

**Comment by judygab** [comment]
Right, there should be a check if the response is empty. I'll add a PR. thanks for pointing it out!

**Comment by pAkalpa** [comment]
@judygab Add Github repo links to your old tutorial videos as well. I'm a newbie to react and web development thanks for your response and your videos. if you need any help regarding Mobile Application Development in Kotlin or ML/DL in Python Contact me(You can find my social media links in my profile [https://github.com/pAkalpa](url) ).
